### ISSUE TITLE
Feature Request: Allow Directory browsing before move/copy

### ISSUE THREAD

**Issue by omarshahine** [koinzhang/common-directory#1]
I have a folder called "Filing Cabinet" that I have added as a Common Directory. It would be wonderful if as part of the move / copy it was possible to navigate the root folder before moving. Otherwise, I need to add all the contents of this directory as common.

**Comment by koinzhang** [comment]
Hi @omarshahine. Thank you for your advice.
I have made the update and now you can enter and exit folders with Enter Folder(⌘+⎇+↓) and Enclosing Folder(⌘+⎇+↑) actions.
Please pull the latest code and reinstall the extension. If you encounter any problems in the process, please feel free to contact me at [slack](https://raycastcommunity.slack.com/archives/D035N2D6H19) or GitHub.
